### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by figsoda**
prodash was not updated since codevis 0.8.3 still depends on prodash 20

### CODE REVIEW

**Comment by sloganking** [comment]
@figsoda

**Comment by figsoda** [comment]
@sloganking I think you might have forgotten your message

**Comment by sloganking** [comment]
> @sloganking I think you might have forgotten your message

What is the reason this was changed from `clap` to `arg`? It seems to still work find if I replace it with `clap` again.

**Comment by figsoda** [comment]
see https://github.com/clap-rs/clap/pull/4180, even though `#[clap()]` still works, `#[arg()]` and `#[command()]` are now recommended since clap v4

**Review by sloganking — APPROVED** [review]

**Comment by sloganking** [comment]
@figsoda Got it. Thanks for the PR!

**Pull request merged**
